config/routes.rb
Inventory::Application.routes.draw do

  devise_for :users

    root 'static_pages#index'
    resources :flosses do
      resources :quantities
    end

end

app/models/floss.rb
class Floss < ActiveRecord::Base
	validates :colour, :brand, presence: true
	validates :colour, uniqueness: true
	belongs_to :user
	has_many :quantities, dependent: :destroy
	has_many :users, through: :quantities
end

app/models/quantity.rb
class Quantity < ActiveRecord::Base
  belongs_to :floss
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :quantities, dependent: :destroy
  has_many :flosses, through: :quantities
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/flosses_controller.rb
class FlossesController < ApplicationController
	before_action :authenticate_user!

	def new
      @floss = Floss.new
	end

	def create
	  @floss = Floss.new(floss_params)
    @floss.save
	  redirect_to flosses_path
  end

  def index
    @quantity = Quantity.new
    @user = current_user
    if params[:brand]
      @flosses = Floss.where(:brand => params[:brand])
    else
      @flosses = Floss.all
    end
    respond_to do |format|
    format.html
    format.json
  end
end

  	def update
    @quantity = Quantity.find(params[:id])
    respond_to do |format|
      if @floss.update_attributes(floss_params)
        format.html { redirect_to flosses_path, notice: 'Floss successfully updated.' }
        format.json
        format.js
      else
        format.html { redirect_to flosses_path, notice: 'Floss not updated' }
        format.json
        format.js
      end
    end
  end

  private

  def floss_params
    params.require(:floss).permit(:brand, :colour)
  end
end

app/controllers/quantities_controller.rb
class QuantitiesController < ApplicationController
	before_action :authenticate_user!
	def new
		@quantity = Quantity.new
	end

	def create
		@floss = Floss.find(params[:floss_id])
		@quantity = @floss.quantities.build(quantity_params)
		@quantity.user = current_user
		@quantity.save
		respond_to do |format|
		  if @quantity.save
		      format.html { redirect_to flosses_path, notice: 'Floss successfully added.' }
		      format.json
		      format.js
	    	else
		      format.html { redirect_to flosses_path, notice: 'Floss not added' }
		      format.json
		      format.js
	    	end
  		end
	end

	def update
	  @floss = Floss.find(params[:floss_id])
	  respond_to do |format|
	    if @quantity.update_attributes(quantity_params)
	      format.html { redirect_to flosses_path, notice: 'Floss successfully updated.' }
	      format.json
	      format.js
	    else
	      format.html { redirect_to flosses_path, notice: 'Floss not updated' }
	      format.json
	      format.js
	    end
	  end
	end

	private

	def quantity_params
	  params.require(:quantity).permit(:quantity)
	end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
	def index
	  if current_user
        redirect_to flosses_path
      else
      # business logic here
      end

	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flosses_helper.rb
module FlossesHelper
end

app/helpers/quantities_helper.rb
module QuantitiesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/flosses/index.html.erb
<br />

<div class="booyah-box col-xs-10 col-xs-offset-1">
  <h1 class="text-center">Your Floss</h1>
  <hr />
	<%= link_to new_floss_path, :class => 'btn btn-primary btn-lg' do %>
    <span class="glyphicon glyphicon-plus"></span> New Floss
  <% end %>
  <%= link_to "DMC", flosses_path(:brand=>"DMC"), :class => 'btn btn-info' %>
  <%= link_to "Anchor", flosses_path(:brand=>"Anchor"), :class => 'btn btn-info' %>
  <%= link_to "Madeira", flosses_path(:brand=>"Madeira"), :class => 'btn btn-info' %>
	<br />
	<br />
	<table class="table table-hover table-condensed">
      <thead>
        <tr>
          <th>Colour</th>
          <th>Quantity</th>
          <th>Update</th>
        </tr>
      </thead>
      <tbody>
        <% @flosses.each do |floss| %>
          <tr>
            <% if floss.quantities.find_by(user_id: current_user) %>
              <td><%= floss.colour %></td>
              <td>
              <%= floss.quantities.first.quantity %>
              <%#= simple_form_for [@quantity, @floss], url: floss_quantity_path(@quantity, @floss), method: 'patch', remote: true do |f| %>
            	    <%#= f.input :quantity, label: false, :size => 5 %>
  		            </td>
  		            <td><%#= f.submit "update", :class => 'btn btn-success' %></td>
                  <%# end %>
            <% else %>
              <td><%= floss.colour %></td>
              <td>
                <%= simple_form_for @quantity, url: floss_quantities_path(floss), remote: true do |f| %>   
                 <%= f.input :quantity, label: false, :size => 5 %>
              </td>
              <td><%= f.submit "update", :class => 'btn btn-success' %></td>
            <% end %>
          </tr>
        <% end %>
        <% end %>
      </tbody>
    </table> 
</div>

app/views/flosses/new.html.erb
<br />
<div class="booyah-box col-xs-10 col-xs-offset-1">
  <h1>Add a new Floss</h1>
  <%= simple_form_for @floss do |f| %>
    <%= f.input :brand, default: '1', :collection => [['DMC', 'DMC'],['Anchor', 'Anchor']] %>
    <%= f.input :colour, :label => "Number or Name" %>
    <br />
    <%= f.submit "Create", :class => 'btn btn-primary' %>
    <br />
  <% end %>
  <br />
</div>

app/views/flosses/update.js.erb
swal("More stash!", "Your floss has been updated", "success")

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Inventory</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
      <% if user_signed_in? %>
        <li><%= link_to 'Your Floss', flosses_path %></li>
        <li><%= link_to 'Sign out', destroy_user_session_path, :method => :delete %></li>
      <% else %>
        <li><%= link_to 'Sign in', new_user_session_path %></li>
        <li><%= link_to 'Sign up', new_user_registration_path %></li>
      <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Inventory</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render "layouts/navbar" %>
<%= render "layouts/messages" %>
<%= yield %>

</body>
</html>

app/views/quantities/_form.html.erb
<%= simple_form_for(@quantity) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :quantity, required: true %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/quantities/create.js.erb
swal("More stash!", "Your floss quantities has been updated", "success")

app/views/quantities/update.js.erb
swal("More stash!", "Your floss quantities has been updated", "success")

app/views/static_pages/index.html.erb
<div class="hero">
  <br />
  <div class="frosty col-xs-10 col-xs-offset-1 text-center">
    <br />
    <h1>Keep track of all your stash</h1>
    <br />
    <h2>Register or Login to start keeping track</h2>
    <br />
    <%= link_to 'Register', new_user_registration_path, :class => 'btn btn-success' %>
    <%= link_to 'Sign In', new_user_session_path, :class => 'btn btn-success' %>
    <br /><br />
  </div>
</div>

<br />
<div class="col-xs-10 col-xs-offset-1 features text-center">
  <div class="col-sm-4">
    <h3>Feature 1</h3>
  </div>

  <div class="col-sm-4">
    <h3>Feature 2</h3>
  </div>

  <div class="col-sm-4">
    <h3>Feature 3</h3>
  </div>
</div>